server:
  host: localhost
  port: 3000
  write_timeout: 10
  read_timeout: 10

database:
  path: files/db/database.db

https:
  coin_cap:
    address: https://api.coincap.io
    client_timeout: 20
    write_timeout: 10
    read_timeout: 10
